---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-k8s
spec:
  selector:
    matchLabels:
      app: httpd_k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: httpd_k8s
    spec:
      containers:
      - name: httpd-container-k8s
        image: httpd:latest
        ports:
        - containerPort: 80
