---
apiVersion: v1
kind: Service
metadata:
  name: httpd-k8s-svc
  labels:
    app: httpd-k8s
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
  selector:
    app: httpd-k8s
